using EdiFabric.Core.Model.Edi;

namespace EdiFabric.Core.Model.Ack
{
    /// <summary>
    /// Interface for generating acknowledgments. 
    /// </summary>
    public interface IAckMan
    {
        /// <summary>
        /// Publishes an item for analysis.
        /// The is the entry point to ack man, which accepts items generated by ediFabric.Framework in the exact sequence 
        /// that was used to produce them.
        /// </summary>
        /// <param name="item">The item to be analyzed.</param>
        void Publish(EdiItem item);

        /// <summary>
        /// Finalizes the analysis and processes whatever is left after the last raised event.
        /// Events are raised when the group trailer tag is encountered and this ensures that 
        /// an acknowledgment is sent for the last group if it does not have a trailer tag.
        /// </summary>
        void Complete();
    }
}
